repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--force-grid-wrap", "2"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  #- repo: https://github.com/pre-commit/mirrors-mypy
   # rev: v1.6.1
   # hooks:
    #  - id: mypy
      #  language: system


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
        - id: pyupgrade
